#!/bin/bash

BUILD_TOOL_PATH = "/Users/ly/Library/Android/sdk/build-tools/"
LAST_SDK_VERSION = ls $BUILD_TOOL_PATH | awk '{print $NF}' |tail -1
BUILD_AAPT_PATH = $BUILD_TOOL_PATH$LAST_SDK_VERSION

#get targetsdk
#echo $((`$BUILD_AAPT_PATH/aapt list -a ./app/build/outputs/apk/debug/app-debug.apk |grep targetSdkVersion |cut -d")" -f 3`))

#get package name
PACKAGE_NAME = $BUILD_AAPT_PATH/aapt dump badging ./app/build/outputs/apk/debug/app-debug.apk |grep package:\ name |awk '{print $2}' | cut -d'=' -f 2

echo $PACKAGE_NAME
